spring:
  main:
    show-banner: false

  thymeleaf:
    cache: false

  datasource:
#    url: jdbc:postgresql://postgres:5432/postgres
#   username: postgres
    url: jdbc:h2:mem:editor;MODE=PostgreSQL
  jpa:
      hibernate.ddl-auto: none

security:
  ignored:
    - '/editar/info'
    - '/editar/health'
    - '/editar/assets/**'
    - '/editar/fonts/**'

endpoints:
  health:
    sensitive: false

server:
  port: ${port:8090}

management:
  context-path: /editar

flags:
  git.push: true
  esquentar.cache: true
  importar: true

eds:
  max-tentativas-token: 3
  max-horas-token: 24
  token:
    desabilitarUsuario: false
  cartas:
    repositorio: "https://github.com/prodest/cartas-de-teste"

fallback:
  eds:
    cartas:
      repositorio: "https://github.com/prodest/cartas-de-teste"

---

spring:
  profiles: desenvolvimento,teste

  datasource:
    url: jdbc:h2:mem:editor;MODE=PostgreSQL


