package br.gov.servicos.editor.security;

import lombok.Getter;

public enum TipoPermissao {
    SALVAR("SALVAR"),
    PUBLICAR("PUBLICAR"),
    DESPUBLICAR("DESPUBLICAR"),
    DESCARTAR("DESCARTAR"),
    EXCLUIR("EXCLUIR"),
    RENOMEAR("RENOMEAR"),
    PUBLICAR_ORGAO_ESPECIFICO("PUBLICAR (ORGAO ESPECIFICO)"),
    DESPUBLICAR_ORGAO_ESPECIFICO("DESPUBLICAR (ORGAO ESPECIFICO)"),
    DESCARTAR_ORGAO_ESPECIFICO("DESCARTAR (ORGAO ESPECIFICO)"),
    EXCLUIR_ORGAO_ESPECIFICO("EXCLUIR (ORGAO ESPECIFICO)"),
    RENOMEAR_ORGAO_ESPECIFICO("RENOMEAR (ORGAO ESPECIFICO)"),
    CADASTRAR("CADASTRAR");

    @Getter
    private final String nome;

    TipoPermissao(String nome) {
        this.nome = nome;
    }
}
