#!/bin/bash

echo 'Instalando novo Editor do Guia de Serviços'
sudo yum remove -y editor-de-servicos
sudo yum install -y editor-de-servicos-latest.rpm

if [ "$?" -ne '0' ]; then
  echo 'Erro na instalação. Abortando...'
  exit -1
fi

echo 'Removendo pacote instalado'
rm -rf editor-de-servicos-latest.rpm

sudo systemctl daemon-reload
sudo systemctl restart editor-de-servicos
