#!/bin/bash
set -x
set -e
set -o pipefail

ssh -F .sshconfig dev '/bin/bash -s' << "EOF"
set -x
set -e
set -o pipefail

cd '/root/docker'
git status
git diff
git stash || true
git pull --rebase
git stash pop || true

export EDS_CARTAS_REPOSITORIO='git@github.com:servicosgovbr/cartas-de-teste.git'

./scripts/update_editor_container
docker-compose restart balanceador

EOF
