#!/bin/bash
set -x
set -e
set -o pipefail

ssh -F .sshconfig dev '/bin/bash -s' << "EOF"
set -x
set -e
set -o pipefail

cd '/root/docker'
git pull --rebase

export PDS_CARTAS_REPOSITORIO='https://github.com/servicosgovbr/cartas-de-teste.git'
export EDS_CARTAS_REPOSITORIO='git@github.com:servicosgovbr/cartas-de-teste.git'

./build-all

docker-compose stop editor1 editor2
docker-compose kill editor1 editor2
docker-compose rm -f editor1 editor2

docker-compose up -d
docker-compose restart balanceador

EOF
