#!/bin/bash
set -x
set -e
set -o pipefail

ssh -F .sshconfig alpha 'sudo /bin/bash -s' << "EOF"
set -x
set -e
set -o pipefail

cd '/root/docker'
git pull --rebase

docker-compose stop
docker-compose kill
docker-compose rm -f

./build

docker-compose up -d

EOF
