#!/bin/bash

echo 'Instalando novo Guia de Serviços...'
sudo yum remove -y editor-de-servicos
sudo yum install -y $1

sudo bash -c 'cat <<-EOF > /etc/sysconfig/guia-de-servicos
# Variáveis de ambiente para configuração do Guia de Serviços

# Ativa o perfil "vagrant" na configuração do Spring.
#
SPRING_PROFILES_ACTIVE=vagrant

EOF
'

echo 'Reiniciando serviço...'
sudo systemctl daemon-reload
sudo systemctl restart editor-de-servicos
