'use strict';

var slugify = require('slugify');
var erro = require('utils/erro-ajax');

module.exports = {
  areasDeInteresse: [
    'Administração',
    'Compras governamentais',
    'Fiscalização do Estado',
    'Normalização e Qualidade',
    'Operações de dívida pública',
    'Orçamento',
    'Patrimônio',
    'Planejamento',
    'Recursos humanos',
    'Serviços Públicos',
    'Outros em Administração',
    'Agropecuária',
    'Abastecimento',
    'Defesa agropecuária',
    'Produção agropecuária',
    'Outros em Agropecuária',
    'Comércio e Serviços',
    'Comercio externo',
    'Defesa do Consumidor',
    'Turismo',
    'Outros em Comércio e serviços',
    'Comunicações',
    'Comunicações Postais',
    'Telecomunicações',
    'Outros em Comunicações',
    'Cultura',
    'Difusão Cultural',
    'Patrimônio Cultural',
    'Outros em Cultura',
    'Defesa Nacional',
    'Defesa Civil',
    'Defesa militar',
    'Outros em Defesa Nacional',
    'Economia e Finanças',
    'Politica econômica',
    'Sistema Financeiro',
    'Outros em Economia e Finanças',
    'Educação',
    'Educação básica',
    'Educação profissionalizante',
    'Educação superior',
    'Outros em Educação',
    'Energia',
    'Combustíveis',
    'Energia elétrica',
    'Outros em Energia',
    'Esporte e Lazer',
    'Esporte comunitário',
    'Esporte profissional',
    'Lazer',
    'Outros em Esporte e Lazer',
    'Habitação',
    'Habitação Rural',
    'Habitação Urbana',
    'Outros em Habitação',
    'Indústria',
    'Mineração',
    'Produção Industrial',
    'Propriedade Industrial',
    'Outros em Industria',
    'Meio ambiente',
    'Água',
    'Biodiversidade',
    'Clima',
    'Preservação e Conservação Ambiental',
    'Outros em Meio Ambiente',
    'Pesquisa e Desenvolvimento',
    'Difusão',
    'Outros em Pesquisa e Desenvolvimento',
    'Previdência Social',
    'Previdência Básica',
    'Previdência Complementar',
    'Outros em Previdência',
    'Proteção social',
    'Assistência à Criança e ao Adolescente',
    'Assistência ao Idoso',
    'Assistência ao Portador de Deficiência',
    'Combate a desigualdade',
    'Cidadania',
    'Outros em Proteção Social',
    'Relações Internacionais',
    'Cooperação Internacional',
    'Relações Diplomáticas',
    'Outros em Relações Internacionais',
    'Saneamento',
    'Saneamento Básico Rural',
    'Saneamento Básico Urbano',
    'Outros em Saneamento',
    'Saúde',
    'Assistência Hospitalar e Ambulatorial',
    'Atendimento básico',
    'Combate a epidemias',
    'Medicamentos e aparelhos',
    'Vigilância Sanitária',
    'Outros em Saúde',
    'Segurança e Ordem Pública',
    'Defesa Civil',
    'Policiamento',
    'Outros em Segurança e Ordem Pública',
    'Trabalho',
    'Empregabilidade',
    'Fomento ao Trabalho',
    'Proteção e Benefícios ao Trabalhador',
    'Relações de Trabalho',
    'Outros em Trabalho',
    'Transportes',
    'Transporte Aéreo',
    'Transporte Ferroviário',
    'Transporte Hidroviário',
    'Transporte Rodoviário',
    'Outros em Transporte',
    'Urbanismo',
    'Infraestrutura urbana',
    'Serviços Urbanos',
    'Outros em Urbanismo'
  ],

  segmentosDaSociedade: [
    'Cidadãos',
    'Empresas',
    'Órgãos e entidades públicas',
    'Demais segmentos (ONGs, organizações sociais, etc)'
  ],

  eventosDaLinhaDaVida: [
    'Apoio financeiro e crédito',
    'Aposentadoria',
    'Contas e Impostos',
    'Cuidados com a saúde',
    'Documentos e certidões',
    'Empreendedorismo e negócios',
    'Estrangeiros no Brasil',
    'Estudos',
    'Exportação de produtos e serviços',
    'Família',
    'Importação de produtos e serviços',
    'Imóveis',
    'Profissão e trabalho',
    'Veículos',
    'Viagem ao exterior'
  ],

  tiposDeCanalDePrestacao: [
    'Aplicativo móvel',
    'E-mail',
    'Fax',
    'Postal',
    'Presencial',
    'SMS',
    'Telefone',
    'Web',
    'Web: Acompanhar',
    'Web: Agendar',
    'Web: Calcular taxas',
    'Web: Consultar',
    'Web: Declarar',
    'Web: Emitir',
    'Web: Inscrever-se',
    'Web: Preencher',
    'Web: Simular'
  ].map(function (c) {
    return {
      id: slugify(c),
      text: c
    };
  }),

  orgaos: _.once(m.request({
    method: 'GET',
    url: '/editar/api/orgaos'
  }).then(function (orgaos) {
    return _.sortBy(orgaos.unidades.map(function (o) {
      var nome = o.nome + ' (' + o.sigla + ')';
      return {
        id: slugify(nome),
        text: nome
      };
    }), function (o) {
      return o.text;
    });
  }, erro))

};
